name: CI
on:
  push:
  pull_request:
  schedule:
  - cron: '0 8 * * 2'
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    strategy:
      fail-fast: false
      matrix:
        java: [8, 11]
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@3f07048e3d294f56e9b90ac5ea2c6f74e9ad0f98 # v3.10.0
      with:
        java-version: ${{matrix.java}}
        distribution: adopt
    - run: sbt -v "+ test"
