name: CI
on:
  push:
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    strategy:
      fail-fast: false
      matrix:
        java: [11]
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@9704b39bf258b59bc04b50fa2dd55e9ed76b47a8 # v4.1.0
      with:
        java-version: ${{matrix.java}}
        distribution: adopt
    - run: sbt -v "+ test"
